SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT * FROM EMP WHERE DEPTNO =10 OR DEPTNO =20;

SELECT * FROM EMP 
WHERE DEPTNO IN (10,20);

SELECT * FROM EMP
WHERE DEPTNO NOT IN (10,20);

SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE SAL >=2000 AND SAL <= 3000;

--p130. Q1
SELECT * FROM EMP
WHERE ENAME LIKE '%S';

--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';

--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO IN (20,30)
AND SAL >2000;

--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO IN (20,30)
MINUS
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE
SAL <= 2000;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 20 AND SAL> 2000
UNION 
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 30 AND SAL> 2000;

--Q4
SELECT * FROM EMP
WHERE SAL < 2000 OR SAL > 3000;

SELECT * FROM EMP
WHERE NOT (SAL >= 2000 AND SAL <=3000);

SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
WHERE ENAME LIKE '%E%' 
AND DEPTNO = 30 
AND SAL <=1000
UNION 
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
WHERE ENAME LIKE '%E%' 
AND DEPTNO = 30 
AND SAL >=2000;

SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
WHERE ENAME LIKE '%E%' 
AND DEPTNO = 30 
AND SAL NOT BETWEEN 1000 AND 2000;

--Q6
SELECT * FROM EMP
WHERE COMM IS NULL 
AND MGR IS NOT NULL 
AND JOB IN ('MANAGER','CLERK')
AND ENAME NOT LIKE '_L%';

SELECT * FROM EMP
WHERE DEPTNO IN (20,30)
AND SAL BETWEEN 2000 AND 3000
ORDER BY SAL, ENAME;

SELECT * FROM EMP
WHERE ENAME LIKE '__A%';

SELECT ENAME AS EMPLOYEE_NAME, DEPTNO AS DEPARTMENT_NO  FROM EMP
ORDER BY DEPTNO, ENAME;

SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;

SELECT LOWER(ENAME, JOB)
FROM EMP;
--에러

SELECT 1
FROM DUAL;
--DUAL은 한 칸 짜리 임시 테이블
SELECT UPPER('aBc'), LOWER('aBc') FROM DUAL;

SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';

SELECT * FROM EMP
WHERE LOWER(ENAME) LIKE LOWER('%AM%');

SELECT ENAME, LENGTH(ENAME)
FROM EMP;

SELECT ENAME, LENGTH(ENAME)
FROM EMP 
WHERE LENGTH(ENAME) >= 5;

SELECT LENGTH('한글'), LENGTHB('한글')
FROM DUAL;

